services:
  - type: web
    name: botwilder
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    pythonVersion: 3.10.13
